/**
 * Report generators: terminal-friendly text and Markdown.
 */
import kleur from 'kleur';
import { categories } from './checks/index.js';

/**
 * Pretty-print to a terminal string. Uses kleur colors.
 */
export function renderTerminal(audit) {
  const lines = [];
  const { score, summary, results, url } = audit;

  lines.push('');
  lines.push(kleur.bold().cyan('  Seolens') + kleur.gray(' — SEO audit'));
  lines.push(kleur.gray('  ' + '─'.repeat(60)));
  lines.push(`  ${kleur.bold('URL:')}    ${url}`);
  lines.push(`  ${kleur.bold('Score:')}  ${scoreColor(score.value)(`${score.value}/100`)} ${kleur.gray(`(${score.grade} — ${score.label})`)}`);
  lines.push(`  ${kleur.bold('Stats:')}  ${kleur.green(summary.passed + ' passed')}, ${kleur.red(summary.critical + ' critical')}, ${kleur.yellow(summary.warning + ' warning')}, ${kleur.blue(summary.info + ' info')}`);
  lines.push('');

  // Group failed checks by category
  const byCategory = groupByCategory(results.filter((r) => !r.passed && r.severity !== 'skip'));
  if (Object.keys(byCategory).length === 0) {
    lines.push(kleur.green('  ✔ All checks passed.'));
  } else {
    lines.push(kleur.bold('  Issues found:'));
    lines.push('');
    for (const [cat, items] of Object.entries(byCategory)) {
      lines.push(kleur.bold().underline(`  ${categories[cat] || cat}`));
      for (const r of items) {
        const icon = severityIcon(r.severity);
        lines.push(`  ${icon} ${kleur.bold(r.label)}`);
        lines.push(`     ${kleur.gray(r.message)}`);
        if (r.fix) lines.push(`     ${kleur.cyan('→ ' + r.fix)}`);
        lines.push('');
      }
    }
  }

  // Passed checks (compact)
  const passed = results.filter((r) => r.passed);
  if (passed.length) {
    lines.push(kleur.gray('  ' + '─'.repeat(60)));
    lines.push(kleur.gray(`  Passed (${passed.length}): `) + passed.map((r) => kleur.green('✔ ') + kleur.gray(r.label)).join(kleur.gray(', ')));
    lines.push('');
  }

  // Pro upsell
  lines.push(kleur.gray('  ' + '─'.repeat(60)));
  lines.push(kleur.gray('  Want full-site crawl, Core Web Vitals, AI fix suggestions, PDF reports?'));
  lines.push(kleur.gray('  → ') + kleur.cyan('Seolens Pro') + kleur.gray(': github.com/bluegalaxydev/seolens-pro'));
  lines.push('');

  return lines.join('\n');
}

/**
 * Render a Markdown report.
 */
export function renderMarkdown(audit) {
  const { score, summary, results, url, fetchedAt } = audit;
  const lines = [];

  lines.push(`# Seolens SEO Audit`);
  lines.push('');
  lines.push(`**URL:** ${url}`);
  lines.push(`**Audited:** ${fetchedAt}`);
  lines.push(`**Score:** **${score.value}/100** (${score.grade} — ${score.label})`);
  lines.push('');
  lines.push(`| Status | Count |`);
  lines.push(`|---|---|`);
  lines.push(`| Passed | ${summary.passed} |`);
  lines.push(`| Critical | ${summary.critical} |`);
  lines.push(`| Warning | ${summary.warning} |`);
  lines.push(`| Info | ${summary.info} |`);
  lines.push('');

  const failed = results.filter((r) => !r.passed && r.severity !== 'skip');
  if (failed.length) {
    lines.push(`## Issues Found`);
    lines.push('');
    const byCategory = groupByCategory(failed);
    for (const [cat, items] of Object.entries(byCategory)) {
      lines.push(`### ${categories[cat] || cat}`);
      lines.push('');
      for (const r of items) {
        const icon = severityIconMd(r.severity);
        lines.push(`#### ${icon} ${r.label}`);
        lines.push('');
        lines.push(`${r.message}`);
        if (r.fix) {
          lines.push('');
          lines.push(`**How to fix:** ${r.fix}`);
        }
        lines.push('');
      }
    }
  } else {
    lines.push('## All checks passed ✓');
    lines.push('');
  }

  const passed = results.filter((r) => r.passed);
  if (passed.length) {
    lines.push(`## Passed Checks (${passed.length})`);
    lines.push('');
    for (const r of passed) lines.push(`- ✓ **${r.label}** — ${r.message}`);
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push(`Generated by [Seolens](https://github.com/bluegalaxydev/seolens). Want full-site crawl, Core Web Vitals, AI suggestions, and PDF reports? → [Seolens Pro](https://github.com/bluegalaxydev/seolens-pro)`);
  lines.push('');

  return lines.join('\n');
}

function groupByCategory(results) {
  const out = {};
  for (const r of results) {
    if (!out[r.category]) out[r.category] = [];
    out[r.category].push(r);
  }
  return out;
}

function severityIcon(s) {
  if (s === 'critical' || s === 'error') return kleur.red('✖');
  if (s === 'warning') return kleur.yellow('⚠');
  if (s === 'info') return kleur.blue('ℹ');
  return kleur.gray('•');
}

function severityIconMd(s) {
  if (s === 'critical' || s === 'error') return '🔴';
  if (s === 'warning') return '🟡';
  if (s === 'info') return '🔵';
  return '⚪';
}

function scoreColor(score) {
  if (score >= 90) return kleur.green().bold;
  if (score >= 75) return kleur.cyan().bold;
  if (score >= 60) return kleur.yellow().bold;
  return kleur.red().bold;
}
